### ISSUE TITLE
运行错误好像是小括号的问题

### ISSUE THREAD

**Issue by Z-figaro** [onezens/AutoLocalization#3]
_compile
    raise error, v # invalid expression
sre_constants.error: unbalanced parenthesis

**Comment by onezens** [comment]
1. python 版本： python -V
2. 将这个路径替换成你电脑中需要国际化的项目的路径后，在终端cd 到RunScript目录下执行 `python AutoGenStrings.py`，最后如果报错的话，将终端错误粘贴下

https://github.com/onezens/AutoLocalization/blob/a4250bcac0467680879c5a094e5c2e67d3058629/AutoLocalization/RunScript/AutoGenStrings.py#L205

**Comment by onezens** [comment]
脚本目前只支持python2

**Comment by Z-figaro** [comment]
确定是英文格式的小括号问题。我对python 一无所知，请问能遍历一下，修改英文括号为中文括号吗？？

**Comment by onezens** [comment]
是项目路径中有中文括号? 还是需要国际化的控件的值里面有中文括号?

**Comment by Z-figaro** [comment]
需要国际化的控件的值，我拿你的demo实测过了；只要有一个，就报错

**Comment by onezens** [comment]
我测试了下，没有问题，你看能提供些更详细的信息不

https://github.com/onezens/AutoLocalization/blob/e349ca319d2286b35f8d0d0c14e31b33cc20de40/AutoLocalization/Profile/Setting/zh-Hans.lproj/View.strings#L8

**Comment by Z-figaro** [comment]
Traceback (most recent call last):
  File "/Users/zhangpeng/Desktop/StarBridgeChain/StarBridgeChain/RunScript/AutoGenStrings.py", line 240, in <module>
    main()
  File "/Users/zhangpeng/Desktop/StarBridgeChain/StarBridgeChain/RunScript/AutoGenStrings.py", line 222, in main
    generateLocalizableFiles(upperFilePath, sourceFilePathName)
  File "/Users/zhangpeng/Desktop/StarBridgeChain/StarBridgeChain/RunScript/AutoGenStrings.py", line 178, in generateLocalizableFiles
    compareWithFilePath(tempFile_Path,targetPath)
  File "/Users/zhangpeng/Desktop/StarBridgeChain/StarBridgeChain/RunScript/AutoGenStrings.py", line 92, in compareWithFilePath
    anotationString = getAnotationOfString(newString_txt,linestr)
  File "/Users/zhangpeng/Desktop/StarBridgeChain/StarBridgeChain/RunScript/AutoGenStrings.py", line 72, in getAnotationOfString
    anotationMatch = re.search(anotationRegex,string_txt)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unbalanced parenthesis
Command /bin/sh failed with exit code 1

**Comment by Z-figaro** [comment]
在根目录生成了一个 名字叫**TempfileOfStoryboardNew.strings** 的文件

**Comment by Z-figaro** [comment]
utf-16/UCS-2,big endian
can not recognize!

我发现这个问题，现在xcode的编码是不是变了？？
