### ISSUE TITLE
环境是Python2.7 运行报错sre_constants.error: multiple repeat，请帮忙看下，谢谢

### ISSUE THREAD

**Issue by singer1026** [onezens/AutoLocalization#4]
------->  sourceFilePath: /Users/singer/Documents/work/project/code/xxxxx/xxxxx/xxxxx/Classes/Home/Base.lproj/*.storyboard  filePath: /Users/singer/Documents/work/project/code/xxxxx/xxxxx/xxxxx/Classes/Home
init with Home.storyboard
- - genstrings Home.storyboard successfully
- - dealing with /Users/singer/Documents/work/project/code/xxxxx/xxxxx/xxxxx/Classes/Home/zh-Hans.lproj/Home.strings
/Users/singer/Documents/work/project/code/xxxxx/xxxxx/xxxxx/Classes/Home/TempfileOfStoryboardNew.strings
/Users/singer/Documents/work/project/code/xxxxx/xxxxx/xxxxx/Classes/Home/zh-Hans.lproj/Home.strings
utf-16/UCS-2,big endian
Traceback (most recent call last):
  File "AutoGenStrings.py", line 242, in <module>
    main()
  File "AutoGenStrings.py", line 224, in main
    generateLocalizableFiles(upperFilePath, sourceFilePathName)
  File "AutoGenStrings.py", line 178, in generateLocalizableFiles
    compareWithFilePath(tempFile_Path,targetPath)
  File "AutoGenStrings.py", line 92, in compareWithFilePath
    anotationString = getAnotationOfString(newString_txt,linestr)
  File "AutoGenStrings.py", line 72, in getAnotationOfString
    anotationMatch = re.search(anotationRegex,string_txt)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: multiple repeat

**Comment by singer1026** [comment]
搞定了 因为storyboard里面有个Label里面字符包含了“*” 导致整个py脚本运行失败。 把*去掉就可以了

**Comment by singer1026** [comment]
包含“*” 星号

**Comment by onezens** [comment]
赞
